spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/education-employment?sslmode=prefer'
    username: education-employment
    password: education-employment

  flyway:
    url: 'jdbc:postgresql://localhost:5432/education-employment?sslmode=prefer'
    user: education-employment
    password: education-employment