domain-events-sqs:
  provider: localstack
  endpoint.url: http://localhost:4566
  queue.name: rp_api_queue
  dlq.name: rp_api_dlq

domain-events-sns:
  provider: localstack

api:
  base:
    url:
      oauth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
