version: 2.1
orbs:
  hmpps: ministryofjustice/hmpps@10
parameters:
  releases-slack-channel:
    type: string
    default: education-skills-work-employment-dev
  java-version:
    type: string
    default: "21.0"
  postgres-version:
    type: string
    default: "16"
  localstack-version:
    type: string
    default: "4"
jobs:
  validate:
    executor:
      name: hmpps/java_localstack_postgres_with_db_name
      jdk_tag: << pipeline.parameters.java-version >>
      postgres_tag: << pipeline.parameters.postgres-version >>
      postgres_db: "education-employment"
      postgres_username: "education-employment"
      postgres_password: "education-employment"
      localstack_tag: << pipeline.parameters.localstack-version >>
    environment:
      DATABASE_ENDPOINT: localhost:5432
      DATABASE_NAME: education-employment
      DATABASE_USERNAME: education-employment
      DATABASE_PASSWORD: education-employment
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
workflows:
  version: 2
  test-only:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
