server:
  shutdown: immediate
build:
  version=${project.version}
management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0
api:
  base:
    url:
      oauth: http://localhost:9090/auth
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT:localhost:5432}/${DATABASE_NAME:education-employment}?sslmode=disable&autosave=conservative'
    username: '${DATABASE_USERNAME:education-employment}'
    password: '${DATABASE_PASSWORD:education-employment}'

  flyway:
    baseline-on-migrate: true
    baseline-version: 1.1
    clean-disabled: false
    enabled: true
    user: '${DATABASE_USERNAME:education-employment}'
    password: '${DATABASE_PASSWORD:education-employment}'
