spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT:localhost:5432}/${DATABASE_NAME:education-employment}?sslmode=disable&autosave=conservative'
    username: '${DATABASE_USERNAME:education-employment}'
    password: '${DATABASE_PASSWORD:education-employment}'

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    user: '${DATABASE_USERNAME:education-employment}'
    password: '${DATABASE_PASSWORD:education-employment}'

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
