CREATE TABLE IF NOT EXISTS revision_info
(
    rev_number bigint GENERATED BY DEFAULT AS IDENTITY,
    rev_time   bigint,
    created_by varchar(30) NOT NULL,

    PRIMARY KEY (rev_number)
);

CREATE TABLE IF NOT EXISTS work_readiness_audit
(
    rev_number          bigint                      NOT NULL,
    rev_type            smallint,
    offender_id         varchar(7)                  NOT NULL,
    booking_id          bigint                      NOT NULL,
    created_by          varchar(32)                 NOT NULL,
    created_date_time   timestamp with time zone    NOT NULL,
    modified_by         varchar(32)                 NOT NULL,
    modified_date_time  timestamp with time zone    NOT NULL,
    schema_version      varchar(16)                 NOT NULL,
    profile_data        jsonb                       NOT NULL,
    notes_data          jsonb,

    PRIMARY KEY (offender_id, rev_number),
    CONSTRAINT fk_revision_info
        FOREIGN KEY (rev_number)
            REFERENCES revision_info (rev_number)
            ON DELETE CASCADE
);
